name: CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Build with Maven
        run: mvn clean install  # Строим проект через Maven

      - name: Run tests
        run: mvn test  # Запуск unit-тестов через Maven

  build-and-deploy:
    runs-on: ubuntu-latest
    needs: build  # Выполняется после успешного билда
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Build Application
        run: mvn clean package  # Сборка JAR файла

      - name: Run Application
        run: |
          java -jar target/*.jar &
          sleep 5

      - name: Deploy to Render using deploy hook
        run: |
          curl --request POST \
          -H "Accept: application/json" \
          -H "Content-Type: application/json" \
          --data '{"key": "cfBdEEjB0bI"}' \
          https://api.render.com/deploy/srv-ctmoiebqf0us738frl6g?key=cfBdEEjB0bI
