name: CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Build with Maven
        run: mvn clean install 

      - name: Run tests
        run: mvn test

  build-and-deploy:
    runs-on: ubuntu-latest
    needs: build  
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Build Application
        run: mvn clean package 

      - name: Run Application
        run: |
          java -jar target/*.jar &
          sleep 5

      - name: Test Application works
        run: curl -v http://localhost:3000

      - name: Deploy to Render
        uses: curl --request POST \
          -H "Accept: application/json" \
          -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
          -H "Content-Type: application/json" \
          --data '{"serviceId": "your-service-id"}' \
          https://api.render.com/v1/services/your-service-id/deploys
